### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by yuvraj11** [flarroca/mdx-portlet#1]
Does this portlet support MySQL DB as the sql-database-portlet does?

**Comment by flarroca** [comment]
Yes, this screenshoot show MySQL and PostgreSQL side by side on the same page.
![08-datasources-2](https://cloud.githubusercontent.com/assets/6661751/24065235/56e849cc-0b48-11e7-8f24-72c7fc229173.png)

Here you can see the datasource configuration for both schemas.
![07-datasources](https://cloud.githubusercontent.com/assets/6661751/24065279/98c78ccc-0b48-11e7-8e2f-255fe009129b.png)

**Comment by yuvraj11** [comment]
Where do I add the XMLs? Like the FoodMart.xml. 

And should I be creating this xml from my database using Pentaho?
